### ISSUE TITLE
编译安装帮助文档在哪里?releases里面的源码你们自己有测试编译过么?

### ISSUE THREAD

**Issue by nojiario** [qiniu/c-sdk#126]
编译安装帮助文档在哪里?releases里面的源码你们自己有测试编译过么?

**Comment by longbai** [comment]
http://developer.qiniu.com/code/v6/sdk/cpp.html 麻烦看下

**Comment by nojiario** [comment]
楼上.... 我问的是这个SDK的编译安装方面的帮助文档,你给个使用文档,不过看到你们在http://developer.qiniu.com/code/v6/sdk/cpp.html 这里补上了库文件就不说啥了.

**Comment by gamegrd** [comment]
mv: cannot stat ‘.deps/CUError.Tpo’: No such file or directory

**Comment by BluntBlade** [comment]
抱歉，6.2.5 这个版本太老，并没有很好地考虑编译需求和问题。
我司会尽快合并最新版本，使用 CMake 构建，大幅减少编译操作。

**Comment by longbai** [comment]
fixed in #127
