### ISSUE TITLE
centos 下编译失败

### ISSUE THREAD

**Issue by gamegrd** [qiniu/c-sdk#128]
make[4]: Entering directory `/home/mige/tools/c-sdk-6.2.5/CUnit/CUnit/Sources/Framework'
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..     -DRELEASE=@RELEASE@ -Wall -W -pedantic -Wshadow -ansi -I/home/mige/tools/c-sdk-6.2.5/CUnit/CUnit/Headers -MT CUError.lo -MD -MP -MF .deps/CUError.Tpo -c -o CUError.lo CUError.c
mv -f .deps/CUError.Tpo .deps/CUError.Plo
mv: cannot stat ‘.deps/CUError.Tpo’: No such file or directory
make[4]: *** [CUError.lo] Error 1

**Comment by BluntBlade** [comment]
抱歉，6.2.5 这个版本太老，并没有很好地考虑编译需求和问题。
我司会尽快合并最新版本，使用 CMake 构建，大幅减少编译操作。

**Comment by longbai** [comment]
fixed in #127
