### ISSUE TITLE
上传策略中多少天删除的问题

### ISSUE THREAD

**Issue by tongzhe7** [qiniu/c-sdk#129]
你好，我想使用七牛上传策略中的多少天后删除功能，就是deleteAfterDays，这个字段。SDK中没有相应字段，我下载的SDK版本时6.2.5，于是我在SDK中添加了相应字段，在源文件rs.c中char* Qiniu_RS_PutPolicy_Token(Qiniu_RS_PutPolicy* auth, Qiniu_Mac* mac)函数中添加，代码如下：
	if (auth->insertOnly) {
		cJSON_AddNumberToObject(root, "insertOnly", auth->insertOnly);
	}
	if(auth->deleteAfterDays >= 0) {
		cJSON_AddNumberToObject(root, "deleteAfterDays", auth->deleteAfterDays);
	}
这样添加后，发现上传的图片并没有删除。
我想咨询一个问题：
    1.   如果我想使用上传策略中的这个超时删除功能，该如何去做，因为我发现6.2.5SDK中没有这个deleteAfterDays字段，但是你们的说明文档里描述了这个字段的功能

**Comment by KevinChenQiniu** [comment]
可以通过 support.qiniu.com 提交个工单，提供一下没有删除的文件的 url 。

**Comment by jemygraw** [comment]
fixed in 6.2.6
