### ISSUE TITLE
在windows下编译不通过

### ISSUE THREAD

**Issue by yupengfei** [qiniu/c-sdk#133]
base_io.c里面

`
#if defined(_MSC_VER)

#define Qiniu_Posix_Pread Qiniu_Posix_Pread2

int Qiniu_Posix_Fstat(Qiniu_Posix_Handle fd, Qiniu_FileInfo* fi)
{
	int ret = 0;
	Emu_FileInfo fi2;

	Qiniu_Zero(fi2);
	ret = Qiniu_Posix_Fstat2(fd, &fi2);
	if (ret < 0) {
		return ret;
	}

	fi->st_size = (Qiniu_Off_T)fi2.st_size;
	fi->st_atime = fi2.st_atime;
	fi->st_mtime = fi2.st_mtime;
	fi->st_ctime = fi2.st_ctime;
	return 0;
}

#else

Qiniu_Error Qiniu_File_Stat(Qiniu_File* self, Qiniu_FileInfo* fi)
{
	Qiniu_Error err;
	if (Qiniu_Posix_Fstat((Qiniu_Posix_Handle)(size_t)self, fi) != 0) {
		err.code = errno;
		err.message = "fstat failed";
	} else {
#if defined(__APPLE__) && defined(TARGET_OS_MAC)
		fi->st_size >>= 32;
#endif
		err = Qiniu_OK;
	}
	return err;
}

#endif
`
这一段会导致windows visual studio下面Qiniu_File_Stat函数未定义，然后io.c等地方引用这个函数会出错。6.2.5没有这个问题。

**Comment by jemygraw** [comment]
请参考：
Windows 程序员

预编译SDK： https://github.com/qiniu/c-sdk-for-windows

已测试代码：https://github.com/qiniudemo/c-sdk-demo
