### ISSUE TITLE
错误	LNK2019	无法解析的外部符号

### ISSUE THREAD

**Issue by dawn520** [qiniu/c-sdk#145]
调用windows sdk出现以下错误怎么解决呢？谢谢
错误	LNK2019	无法解析的外部符号 "struct _Qiniu_Error __cdecl Qiniu_RSF_ListFiles(struct _Qiniu_Client *,struct _Qiniu_RSF_ListRet *,char const *,char const *,char const *,char const *,int)" (?Qiniu_RSF_ListFiles@@YA?AU_Qiniu_Error@@PAU_Qiniu_Client@@PAU_Qiniu_RSF_ListRet@@PBD222H@Z)，该符号在函数 "public: void __thiscall Qiniu::getFilesList(void)" (?getFilesList@Qiniu@@QAEXXZ) 中被引用	qiniuQT	E:\project\qt\qiniuQT\qiniu.obj	1

**Comment by dawn520** [comment]
mac下也是报同样的错误
Undefined symbols for architecture x86_64:
  "Qiniu_RSF_ListFiles(_Qiniu_Client*, _Qiniu_RSF_ListRet*, char const*, char const*, char const*, char const*, int)", referenced from:
      Qiniu::getFilesList() in qiniu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qiniuQT.app/Contents/MacOS/qiniuQT] Error 1

**Comment by jemygraw** [comment]
你是使用库引用的方式，还是直接使用源码编译的？

**Comment by dawn520** [comment]
@jemygraw windows下，我使用的是你们提供的windows预编译sdk，mac下我是自己编译的，上传文件都正常，但是获取一个bucket下面的文件 使用Qiniu_RSF_ListFiles就会出现以上错误。

**Comment by litianqi1996** [comment]
hi https://github.com/qiniu/c-sdk-for-windows 
直接在github上下载下试试 ，新版本没有打tag  。不要用带tag 的版本试试

**Comment by dawn520** [comment]
@litianqi1996 我是直接git clone下来的
