### ISSUE TITLE
compile error with openssl 1.1.0 

### ISSUE THREAD

**Issue by cambrian07** [qiniu/c-sdk#150]
qiniu/auth_mac.c: In function ‘Qiniu_Mac_Auth’:
qiniu/auth_mac.c:54:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;

**Comment by jemygraw** [comment]
麻烦给下编译的系统环境，还有使用的IDE之类的。

**Comment by cambrian07** [comment]
树莓派3B+ 
系统是Raspbian最新的系统
openssl的版本号是1.1.0
其他都是按照你们提供的教程进行编译的。

**Comment by litianqi1996** [comment]
这个是openssl 版本的问题 我们后续会添加兼容 可以先使用下 openssl 1.0.2版本源码

**Comment by cambrian07** [comment]
好的

**Comment by litianqi1996** [comment]
已添加兼容
