### ISSUE TITLE
Qiniu_Io_PutFile上传文件后，如何取得对应的url?

### ISSUE THREAD

**Issue by tms2003** [qiniu/c-sdk#196]
我使用https://github.com/qiniu/c-sdk/blob/master/examples/up_form_upload.c的代码上传了文件，但如何取得对应的url呢？
我查看Qiniu_Io_PutRet的定义，但只有hash和key，没有对应的url!java版本就是非常的完整！

**Comment by bachue** [comment]
参考 https://developer.qiniu.com/kodo/1255/cpp#4
