### ISSUE TITLE
cmake 编译失败  vs2019 windows x64

### ISSUE THREAD

**Issue by RichardsATcn** [qiniu/c-sdk#199]
N:\qiniu\c-sdk>cmake --build build --config Release
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

MSBUILD : error MSB1009: 项目文件不存在。
开关:ALL_BUILD.vcxproj

N:\qiniu\c-sdk>cmake -DCURL_ROOT=O:\vcpkg\installed\x64-windows\ -DOPENSSL_ROOT_DIR=o:\vcpkg\installed\x64-windows\ -S . -B build
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Src file: b64/b64.c;b64/urlsafe_b64.c cJSON/cJSON.c qiniu/auth_mac.c;qiniu/base.c;qiniu/base_io.c;qiniu/cdn.c;qiniu/conf.c;qiniu/emu_posix.c;qiniu/fop.c;qiniu/http.c;qiniu/io.c;qiniu/multipart_upload.c;qiniu/qetag.c;qiniu/reader.c;qiniu/recorder.c;qiniu/recorder_key.c;qiniu/recorder_utils.c;qiniu/resumable_io.c;qiniu/rs.c;qiniu/rsf.c;qiniu/tm.c
CMake Error: Error: generator : Visual Studio 16 2019
Does not match the generator used previously: NMake Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1000 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1141:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1141 (cmake_language)
  gtests/CMakeLists.txt:18 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
See also "N:/qiniu/c-sdk/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/qiniu/c-sdk/files/10090091/CMakeOutput.log)

**Comment by bachue** [comment]
@RichardsATcn 
```
cmake -DCURL_ROOT=<VCPKG PATH>\installed\<VCPKG TRIPLET>\ -DOPENSSL_ROOT_DIR=<VCPKG PATH>\installed\<VCPKG TRIPLET>\ -S . -B build
```

这个还没执行吧？
